spring:
  application:
    name: learn-spring-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:30b
    google:
      genai:
        api-key:
        chat:
          options:
            model: gemini-2.5-flash-lite
            temperature: 0.9

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG