spring.application.name=productionreadyfeature


spring.datasource.url=jdbc:mysql://localhost:3306/post?useSSL=false
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#DevTools

#spring.devtools.restart.enabled = false;
#spring.devtools.restart.exclude = filepath**
