spring.application.name=SpringSecurityApp
spring.datasource.url=jdbc:mysql://localhost:3306/springsecurityapp?useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##security configs
#spring.security.user.name=root
#spring.security.user.password=pass

#JWT
jwt.secretKey = abcduytwaklcfmnznvgzl7ernz943vkfhnz94worjhzr9onrvhorilrmrjrz




#Oauth Clients Config
spring.security.oauth2.client.registration.google.client-id=564405635327-m3icmge10dvin5knqt8v740n81kqunru.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.github.client-id=564405635327-m3icmge10dvin5knqt8v740n81kqunru.apps.googleusercontent.com
spring.security.oauth2.client.registration.github.client-secret=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
spring.security.oauth2.client.registration.facebook.client-id=564405635327-m3icmge10dvin5knqt8v740n81kqunru.apps.googleusercontent.com
spring.security.oauth2.client.registration.facebook.client-secret=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
